export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";
export const  GET_CATEGORY_SUCCESS = " GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ID = "GET_CATEGORY_ID";